USE [guest]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SURVEY_BOOKS_RENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BOOK_ID] [int] NULL,
	[CATEGORY_ID] [int] NULL,
	[PRICE] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_EMP] [int] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_EMP] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


